### ISSUE TITLE
Please use the correct definition of SP and AP

### ISSUE THREAD

**Issue by yqzhishen** [UtaUtaUtau/nnsvs-db-converter#1]
According to DiffSinger reserved phoneme definition, `SP` means space (pause) and `AP` means aspiration (breath). Reference: https://github.com/openvpi/DiffSinger/blob/main/docs/BestPractices.md#dictionaries

Your script uses the length to distinguish `SP` and `AP`, which is not correct: https://github.com/UtaUtaUtau/nnsvs-db-converter/blob/main/db_converter.py#L47-L51

There is already a naive algorithm to classify `SP` and `AP` in case all consonants and vowels are labeled: https://github.com/openvpi/MakeDiffSinger/blob/main/acoustic_forced_alignment/enhance_tg.py#L105-L172

The algorithm works well even on automatically labeled Chinese datasets, at least better than nothing.

**Comment by UtaUtaUtau** [comment]
Added the breath detection algorithm in [this commit.](https://github.com/UtaUtaUtau/nnsvs-db-converter/commit/06e453b149ae62af1bc13e72e386fcc94ef861e3) Thanks for the suggestion!
